# file: create-mac-pools.yml

 - name : Create HPC MAC Pools
   ucs_mac_pool:
     hostname: "{{ this_ucs_hostname }}"
     username: "{{ this_ucs_username }}"
     password: "{{ this_ucs_password }}"
     name: "{{ item.name }}"
     order: "sequential"
     first_addr: "{{ item.first }}"
     last_addr: "{{ item.last }}"
   with_items: "{{ hpc_mac_pools }}"

