# file: create-ip-pools.yml

 - name : Create UCS IP Pools
   ucs_ip_pool:
     hostname: "{{ this_ucs_hostname }}"
     username: "{{ this_ucs_username }}"
     password: "{{ this_ucs_password }}"
     name: "{{ item.name }}"
     order: "sequential"
     first_addr: "{{ item.first }}"
     last_addr: "{{ item.last }}"
     subnet_mask: "{{ item.netmask }}"
     default_gw: "{{ item.gateway }}"
     primary_dns: "{{ item.dns1 }}"
     secondary_dns: "{{ item.dns2 }}"
   with_items: "{{ hpc_ip_pools }}"

